# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Night shift (ajuste de temperatura de color según hora del día - reemplazo del CTM que crashea Hyprland)
exec-once = $HOME/.config/hypr/scripts/Hyprsunset.sh init
